### ISSUE TITLE
action.devices.traits.Cook does not publish mqtt messages to client

### ISSUE THREAD

**Issue by MDCHAMP** [electrofun-smart/my-smart-home-java-mqtt#3]
the cook trait does not call publishMqtt() and so any subscribed devices are not able to respond to cooking requests. I'm not sure what the behavior that is expected but I suggest a quick fix that sends a message like {"cookingMode", "Quantity"} to the mqtt service.

**Comment by MDCHAMP** [comment]
I have added basic functionality that just sends a message like {"start" : true} over the service, but I think a better approach is to send more of the related data. I am unfamiliar with the publishMqtt() function, is there some way to send more fields in the mqtt message?

I will add a PR for the patch I have in anycase.

**Comment by electrofun-smart** [comment]
Yes, you can send more json fields in the message. Mqtt has a limited size of message depending how the broker is configured, but should be enough to send a couple of fields.
