### ISSUE TITLE
Broker details are hardcoded to MyMqtt class

### ISSUE THREAD

**Issue by MDCHAMP** [electrofun-smart/my-smart-home-java-mqtt#4]
Is it possible to quickly abstract the broker details (username, password etc) to a seperate file that can be added to the gitignore so that we don't accidently commit our details in patches?

I'm not really very good with java, is there a straightforward way to do this?

**Comment by electrofun-smart** [comment]
Hi Max, I will investigate it

**Comment by electrofun-smart** [comment]
Fixed, I created a resource properties called mqtt.properties and added it on gitignore
